// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGg21SJ4Vrq6f-ByIyxeHBALaGuuXWxfs',
    appId: '1:1029869072459:android:83f54f8c5ff593624f9dce',
    messagingSenderId: '1029869072459',
    projectId: 'fooddeliveryyazbox',
    storageBucket: 'fooddeliveryyazbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7pUj3RFPvvGNAEzEb9rgaIogPcgCNjVU',
    appId: '1:1029869072459:ios:ce7ecff274df238c4f9dce',
    messagingSenderId: '1029869072459',
    projectId: 'fooddeliveryyazbox',
    storageBucket: 'fooddeliveryyazbox.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3ra1BPw2Ak-SFK1FK4RhsaNNRWIGUKM',
    appId: '1:1029869072459:web:7f1691fbf59ec5494f9dce',
    messagingSenderId: '1029869072459',
    projectId: 'fooddeliveryyazbox',
    authDomain: 'fooddeliveryyazbox.firebaseapp.com',
    storageBucket: 'fooddeliveryyazbox.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP3ra1BPw2Ak-SFK1FK4RhsaNNRWIGUKM',
    appId: '1:1029869072459:web:4b1cb9993027352d4f9dce',
    messagingSenderId: '1029869072459',
    projectId: 'fooddeliveryyazbox',
    authDomain: 'fooddeliveryyazbox.firebaseapp.com',
    storageBucket: 'fooddeliveryyazbox.firebasestorage.app',
  );

}